apiVersion: v1
kind: Service
metadata:
  name: x-service
  namespace: istio-poc
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    component: x-api
  ports:
    - port: 3000
      targetPort: 80